import type { Metadata } from "next";

import { Geist, Geist_Mono, Outfit } from "next/font/google";

import "./globals.css";
import Dockbar from "@/components/Dockbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const outfit = Outfit({
  subsets: ['latin'],
  weight: ['100', '400', '700', '900'], // Choose the weights you need
  variable: '--font-outfit', // Optional: for CSS variables
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="sphere-background">
          <div className="sphere-gradient"></div>
        </div>
        <Dockbar />
        {children}
      </body>
    </html>
  );
}

